export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT';
export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT';
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';

export const TOGGLE_VIDEOS = 'TOGGLE_VIDEOS';
export const TOGGLE_PICTURES = 'TOGGLE_PICTURES';
export const TOGGLE_VIEW = 'TOGGLE_VIEW';
export const TOGGLE_SORT = 'TOGGLE_SORT';
export const TOGGLE_AUTOPLAY = 'TOGGLE_AUTOPLAY';