export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT';
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const LOG_FETCH = 'LOG_FETCH';
export const NOT_FETCH = 'NOT_FETCH';
export const INC_FETCH_COUNTER = 'INC_FETCH_COUNTER';

export const EMPTY_POSTS = 'EMPTY_POSTS';
export const EMPTY_TAGS = 'EMPTY_TAGS';
export const FILTER_TAG = 'FILTER_TAG'
export const SORT_POSTS = 'SORT_POSTS'

export const TOGGLE_VIDEOS = 'TOGGLE_VIDEOS';
export const TOGGLE_PICTURES = 'TOGGLE_PICTURES';
export const TOGGLE_VIEW = 'TOGGLE_VIEW';
export const TOGGLE_SORT = 'TOGGLE_SORT';
export const TOGGLE_AUTOPLAY = 'TOGGLE_AUTOPLAY';
export const MOBILE_SEARCH = 'MOBILE_SEARCH';
export const MOBILE_SETTINGS = 'MOBILE_SETTINGS';

export const ADD_SUBREDDIT = 'ADD_SUBREDDIT';
export const DELETE_SUBREDDIT = 'DELETE_SUBREDDIT';

